### ISSUE TITLE
Remove people in camp

### ISSUE THREAD

**Issue by Xerthes** [hitobito/hitobito#16] opened 2016-03-23 10:00 UTC
It's impossible to remove the people enter by leader camp in new module camp.
Just possible himself

**Comment by hupf** [comment] 2016-03-24 14:45
Hi @Xerthes 

Thanks for reporting the issue. Can you elaborate some more on your problem: I suppose you are using the PBS wagon, is that correct? Are you saying that only the Person with ```Event::Camp::Role::Leader``` can remove a Person (e.g. a participant) from an ```Event::Camp``` but other people should be able to do this? What is your desired/expected behavior?

Mathis

**Comment by Xerthes** [comment] 2016-03-25 13:30
Hi @hupf 

Yes, i use hitobito with PBS. You have quite understood the problem.
by against, it would be that the camp leaders (not just the main leader) can remove members of Event :: Camp

Sorry, i never before use Github and speak English not good ;)

**Comment by adriananderegg** [comment] 2016-03-26 13:50
Hi both!
@hupf I tried to reproduce the issue and noticed the following:
when a camp is in state "created", the flag event_participants_can_cancel is not considered. 

I opened a camp in state created. Flag event_participants_can_cancel is set. Only the camp leader can remove the participant again.
I set the camp to state confirmed. Now the camp leader, any other leader of the camp and the participant himself can remove the participation. 

Hope that helps. 

@Xerthes: if you prefere to write in French, feel free, I could translate.

**Comment by hupf** [comment] 2016-03-31 09:27
Okay guys, sorry for the delay. Thanks @adriananderegg for your additions. I've looked up the concerning abilities and unfortunately failed to reproduce the case.

So, according to the abilities, someone may cancel another's participation independent of the camp's state if he has either one of the group role permissions: ```group_full```, ```group_and_below_full```, ```layer_full``` or ```layer_and_below_full```:
```
group_full              Event::Participation            cancel                          in_same_group
group_and_below_full    Event::Participation            cancel                          in_same_group_or_below
layer_full              Event::Participation            cancel                          in_same_layer
layer_and_below_full    Event::Participation            cancel                          in_same_layer
```

Or if he has the event role permission ```participations_full``` (also independent of the state):
```
any                     Event::Participation            cancel                          for_participations_full_events
```

The ```can_cancel``` flag only comes into play when cancelling own participations; this is only possible when camp is in confirmed state:
```
any                     Event::Participation            cancel_own                      her_own_if_participant_can_cancel
```

So according to the the camp roles permissions the following roles may cancel other's participations at any state:
* Lagerleitung (```Event::Camp::Role::Leader```)
* Leitung (```Event::Camp::Role::AssistantLeader```)

And the following may not:
* Küche / Helfer/-in
* Teilnehmer/-in
* Leiter-/in Sicherheitsaktivität Berg
* Leiter-/in Sicherheitsaktivität Winter
* Leiter-/in Sicherheitsaktivität Wasser
* Abteilungsleitung
* Coach
* Betreuung Sicherheitsaktivität Berg
* Betreuung Sicherheitsaktivität Winter
* Betreuung Sicherheitsaktivität Wasser

I've tested this locally using the stable Branches of core/pbs/youth and with a camp in state created. I can both:
* cancel another user's participation
* and delete the participant's camp role

with users with role Lagerleitung or Leitung.

Have I understood the problem? What version are you using? Can you give me more details on the group/camp roles of the involved users?

P.S. @Xerthes tu peux répondre en français, si tu veux...

**Comment by hupf** [comment] 2016-05-19 12:05
I close this issue due to missing response and suppose it is solved. Reopen otherwise.

**Closed by hupf** 2016-05-19 12:05 UTC
